name: Publish on GitHub, CurseForge & Modrinth

on: workflow_dispatch

env:
  MINECRAFT_VERSION: 1.20.4
  JAVA_VERSION: 17
  MOD_VERSION: 0.0.4a
  MODRINTH_TOKEN: ${{ secrets.PUBLISH_MODRINTH_TOKEN }}
  CURSEFORGE_TOKEN: ${{ secrets.PUBLISH_CURSEFORGE_TOKEN }}
  GITHUB_TOKEN: ${{ secrets.PUBLISH_GITHUB_TOKEN }}
  PRODUCTION: true

permissions:
  contents: write

jobs:
  Build-Publish-LinuxNatives:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Save Version
        run: ./gradlew saveVersion --console=plain

      - name: Build Mod
        run: ./gradlew build --console=plain

      - name: Publish Mod (CurseForge/Modrinth/GitHub)
        uses: Kir-Antipov/mc-publish@v3.3
        with:
          # modrinth-id: 
          # modrinth-token: ${{ env.MODRINTH_TOKEN }}

          # curseforge-id: 
          # curseforge-token: ${{ env.CURSEFORGE_TOKEN }}

          github-token: ${{ env.GITHUB_TOKEN }}

          name: "CodeNode Microcontrollers v${{ env.MOD_VERSION }} for Minecraft ${{ env.MINECRAFT_VERSION }}"
          version: "${{ env.MOD_VERSION }}-${{ env.MINECRAFT_VERSION }}"
          version-type: alpha
          
          loaders: fabric
          game-versions: "${{ env.MINECRAFT_VERSION }}"

      - name: Compile Natives
        run: ./gradlew compileNatives --console=plain

      - name: Upload Linux Binary
        uses: softprops/action-gh-release@v2
        with:
          files: build/natives/libcnmcu*
          tag_name: "${{ env.MOD_VERSION }}-${{ env.MINECRAFT_VERSION }}"
  WindowsNatives:
    runs-on: windows-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17

      - name: Save Version
        run: ./gradlew saveVersion --console=plain

      - name: Compile Natives
        run: ./gradlew compileNatives --console=plain

      - name: Upload Windows Binary
        uses: softprops/action-gh-release@v2
        with:
          files: build/natives/libcnmcu*
          tag_name: "${{ env.MOD_VERSION }}-${{ env.MINECRAFT_VERSION }}"

  MacOSNatives:
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          distribution: "temurin"
          java-version: 17
          
      - name: Save Version
        run: ./gradlew saveVersion --console=plain

      - name: Compile Natives
        run: ./gradlew compileNatives --console=plain

      - name: Upload Macos Binary
        uses: softprops/action-gh-release@v2
        with:
          files: build/natives/libcnmcu*
          tag_name: "${{ env.MOD_VERSION }}-${{ env.MINECRAFT_VERSION }}"
